sonar.projectKey=faustine-cicd-tasklist-frontend

sonar.sources=src
sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.ts,src/__tests__/**/*.tsx
sonar.coverage.exclusions=src/types/**
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.config.ts,src/main.tsx,src/vite-env.d.ts,src/__tests__/**
sonar.typescript.lcov.reportPaths=coverage/lcov.info